### PR TITLE
Fix memory leak when a workflow with an active internal timer is destroyed

### LINKED ISSUE #177: [Bug] Got the response to undefined request due to the memory leak in the WF worker
### Describe the bug

Sometimes when a child worker process throws an exception, the parent worker process throws the following panic error:
```
PanicError: flush queue: SoftJobError:
	codec_execute:
	sync_worker_exec:
	sync_worker_exec_payload: LogicException: Got the response to undefined request 10389 in /srv/vendor/temporal/sdk/src/Internal/Transport/Client.php:60
```
and after it:
```
PanicError: unknown command CommandType: ChildWorkflow, ID: edfb1479-3d88-407e-a428-7e304e0d7bdf, possible causes are nondeterministic workflow definition code or incompatible change in the workflow definition 
```
Screenshot 2022-05-26 at 20 57 30

### Environment/Versions

- Temporal Version: 1.16.2 and 1.2.0 SDK
- We use Kubernetes

### Additional context

We tried to scale the pods so that can be split in different zones for fault tolerance. Maybe that causing these problems.

### PR DESCRIPTION
**Pull request by roxblnfk**
## What was changed

- Fixed memory leaks in the case when an uncompleted workflow with an active internal timer (see awaitWithTimeout) is destroyed.
- Call `gc_collect_cycles()` after each Workflow destroy.
- Remove the `WorkflowContext::$timers` collection. Ut is unnecessary since Temporal PHP SDK 2.0 .
- Remove the `WorkflowContext::$asyncAwaits` collection because it is unnecessary.
- Remove unused $loop parameter from the `Temporal\Internal\Transport\Client` constructor.
- Other small improvements.

## Why?

In the case when the Workflow Worker processes many workflows at the same time
and their number exceeds the value of the `cache_size` parameter, the Workflow Worker will destroy some waiting workflows.
But the Workflow Worker incorrectly destroys workflows with active internal timers: timer promises
will remain in memory. This leads to memory leak.

## Checklist

1. Closes #177
2. Autotests added

### CODE REVIEW

File: src/Internal/Workflow/WorkflowContext.php [hunk 1]
```diff
@@ -481,8 +501,7 @@ public function awaitWithTimeout($interval, ...$conditions): PromiseInterface
     public function resolveConditions(): void
     {
         foreach ($this->awaits as $awaitsGroupId => $awaitsGroup) {
-            foreach ($awaitsGroup as $i => $cond) {
-                [$condition, $deferred] = $cond;
+            foreach ($awaitsGroup as $i => [$condition, $deferred]) {
                 if ($condition()) {
                     $deferred->resolve();
```
Comment (wolfy-j) [inline src/Internal/Workflow/WorkflowContext.php:506]: do we actually still need it? Maybe we can try to delete whote awaitGroup without rejecting each of internal promises (they are our promises anyway).

**Review by wolfy-j — APPROVED** [review]

File: src/Internal/Workflow/WorkflowContext.php (hunk 1 above)
Comment (roxblnfk) [reply src/Internal/Workflow/WorkflowContext.php:506]: This shuld be tested
